name: flutter_calendar
description: A calendar widget that uses Material Design.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.14.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true