name: flutter_calendar
description: A calendar widget that uses Material Design.
version: 0.0.1
author: Eric Windmill <ericwindmill.com>
homepage: https://github.com/apptreesoftware/flutter_calendar

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.0
  tuple: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true